name: directory-listing
on: [push]

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main    #checkout different branch

      - name: Install zip
        uses: montudor/action-zip@v0.1.0

      - name: Zip output
        run: zip -qq -r media.zip media
        working-directory: public-www/legacy/albrecht-von-haller.ch

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: public-www      #directory to generate index

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public-www'      # upload generated folder

  deploy:
    needs: pages-directory-listing
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
